stages:
  - install dependencies
  - lint
  - build
  - test

.ci-back:
  image: node
  tags:
    - docker
  before_script:
    - cd backendsqlite

.ci-back-write-cache:
  extends: .ci-back
  cache:
    key: back-$CI_COMMIT_REF_SLUG
    paths:
      - backendsqlite/node_modules/
    policy: push

.ci-back-read-cache:
  extends: .ci-back
  cache:
    key: back-$CI_COMMIT_REF_SLUG
    paths:
      - backendsqlite/node_modules/
    policy: pull

install back dependencies:
  extends: .ci-back-write-cache
  stage: install dependencies
  script:
    - npm ci --prefer-offline

lint back:
  extends: .ci-back-read-cache
  stage: lint
  script:
    - npm run lint

build back:
  extends: .ci-back-read-cache
  stage: build
  script:
    - npm run build

test-unit back:
  stage: test
  extends: .ci-back-read-cache
  script:
    - npm run test:spec

test-e2e back:
  stage: test
  extends: .ci-back-read-cache
  script:
    - npm run test:e2e