stages:
  - install dependencies
  - lint
  - build
  - test

.ci-front:
  image: node
  tags:
    - docker
  before_script:
    - cd frontend
    - cp .env.ci .env

.ci-front-write-cache:
  extends: .ci-front
  cache:
    key: front-$CI_COMMIT_REF_SLUG
    paths:
      - frontend/node_modules/
    policy: push

.ci-front-read-cache:
  extends: .ci-front
  cache:
    key: front-$CI_COMMIT_REF_SLUG
    paths:
      - frontend/node_modules/
    policy: pull

install front dependencies:
  extends: .ci-front-write-cache
  stage: install dependencies
  script:
    - npm ci --prefer-offline

lint front:
  extends: .ci-front-read-cache
  stage: lint
  script:
    - npm run lint
  needs:
    - install front dependencies

build front:
  tags:
    - docker
  image: sebastienviardot/rnenvsv:buster
  stage: build
  extends: .ci-front-read-cache
  script:
  - ./genereapk.sh
  artifacts:
    paths:
      - frontend/public/*
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

test-e2e front:
  tags:
    - docker 
    - perso
  image: cypress/base:latest
  stage: test
  extends: .ci-front-read-cache
  script:
    - npm ci --prefer-offline
    - npm install -g wait-on
    - npm run web &
    - wait-on http://localhost:19006
    - npm run test
  needs:
    - install front dependencies
  artifacts:
    when: always
    paths:
      - frontend/cypress/videos/*

