stages:
  - install dependencies
  - lint
  # - build
  - test

.ci-front:
  image: node
  tags:
    - docker
  before_script:
    - cd frontend

.ci-front-write-cache:
  extends: .ci-front
  cache:
    key: front-$CI_COMMIT_REF_SLUG
    paths:
      - frontend/node_modules/
    policy: push

.ci-front-read-cache:
  extends: .ci-front
  cache:
    key: front-$CI_COMMIT_REF_SLUG
    paths:
      - frontend/node_modules/
    policy: pull

install front dependencies:
  extends: .ci-front-write-cache
  stage: install dependencies
  script:
    - npm ci --prefer-offline

lint front:
  extends: .ci-front-read-cache
  stage: lint
  script:
    - npm run lint
  needs:
    - install front dependencies

# build front:
#   extends: .ci-front-read-cache
#   stage: build
#   script:
#     - npm run build

test-e2e front:
  tags:
    - docker 
  image: cypress/base:16.18.1
  stage: test
  extends: .ci-front-read-cache
  script:
    - npm ci --prefer-offline
    - npm run web &
    - |
      # Wait for the server to be up and running
      count=0
      until wget --spider http://localhost:19006 2>/dev/null; do
        if [ $count -eq 60 ]; then
          echo "Server not available after 1 minute, exiting"
          exit 1
        fi
        printf '.'
        sleep 1
        count=$((count+1))
      done
    - npm run test
  needs:
    - install front dependencies